### ISSUE TITLE
allow function without 'secrets' access in 1.3+

### ISSUE THREAD

**Issue by randallt** [wavefrontHQ/wavefront-collector-for-kubernetes#122]
Hi,

I upgraded from v1.2.6 to v1.3.2 and noticed that my log got spammed with a lot of messages regarding no access to secrets. I don't think we would want to give the collector access to secrets, and this should be fine. We should be able to configure the collector to operate without access to secrets and not spam the log.

**Comment by randallt** [comment]
I realize that the log message would disappear if we gave the collector 'secrets' access. But that's not something we want to do.

**Comment by randallt** [comment]
If this only needs secret access to the namespace, then we probably don't want to give it cluster-wide secret access.

**Comment by JSchuenke** [comment]
Hey @randallt! Thanks for your patience. We've decided to add a feature around this. We want to disable usage of Secrets through the ClusterRole definition given to the collector. So, if the collector doesn't have access to Secrets in the ClusterRole, we would log an appropriate WARNING or INFO message during startup and then no longer listen for Secrets. Does this sound like something that would solve your issue?

**Comment by randallt** [comment]
Yes. That should be fine.

**Comment by josephgee** [comment]
Fixed in https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/pull/137, should be in 1.3.5 release shortly.
