### ISSUE TITLE
Cannot build local executable without kubectl

### ISSUE THREAD

**Issue by joancafom** [wavefrontHQ/wavefront-collector-for-kubernetes#188]
Hi! 

I am facing issues trying to build the local executable in an environment that doesn't have `kubectl` installed. It seems that it might be related to some changes introduced in a recent refactor (#169):

_Makefile_
```
...
AWS_REGION=us-west-2
ECR_ENDPOINT=${WAVEFRONT_DEV_AWS_ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

+ K8S_ENV=$(shell cd $(DEPLOY_DIR) && ./get-k8s-cluster-env.sh)
```

When I try to build the executable using `make build`, as the README [indicates](https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes#building), I get the following:

```
$ make build
...
./get-k8s-cluster-env.sh: line 3: kubectl: command not found
```

I don't think there should be a dependency with `kubectl` if one is only looking to build the local executable. How can I make it?

**Comment by joancafom** [comment]
Any thoughts on this?

**Comment by FraPazGal** [comment]
Bumping this in case someone can take a look, thx!

**Comment by priyaselvaganesan** [comment]
Created [K8SSAAS-1051](https://jira.eng.vmware.com/browse/K8SSAAS-1051) to prioritize this issue.
