### ISSUE TITLE
Log4j fix introduced in wavefront proxy version 10.12; current release is 10.11.

### ISSUE THREAD

**Issue by n0rig** [wavefrontHQ/wavefront-collector-for-kubernetes#328]
Seems that this commit shows what needs to be updated:
* https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/commit/a21254e3bbd231730a681f68b92a5dc9e8727455

**Comment by mmichael** [comment]
We updated the Kubernetes deployment to use the wavefront proxy version 10.12 on 12-17.  #327
