### ISSUE TITLE
kubernetes.node.cpu.request does not match kubectl describe node and GKE metrics

### ISSUE THREAD

**Issue by austinpray-mixpanel** [wavefrontHQ/wavefront-collector-for-kubernetes#365]
Hey there! I've got the wavefront-collector 1.8.0 deployed to a GKE cluster. I'm trying to root cause why our kubernetes.node.cpu.request from wavefront-collector is showing 142 cores while the request reported by kubectl describe and GKE comes in at 7.39 cores.

![Screen Shot 2022-02-23 at 12 31 11 PM](https://user-images.githubusercontent.com/71290498/155384347-28ab1780-7c3d-46cf-8fba-928d4bd51367.png)

This query is from the default wavefront managed kubernetes node dashboard: `aliasMetric(ts("kubernetes.node.cpu.request"), "CPU Request")/1000`

When I do a `kubectl describe node/...` I get the correct information:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                   Requests     Limits
  --------                   --------     ------
  cpu                        7393m (23%)  8250m (25%)
```

Which matches GKE:

![image](https://user-images.githubusercontent.com/71290498/155384488-bdc48994-2c26-4d42-a44d-15041183226f.png)

The 142 cores number for this node is not mysterious to me. I see on this node we are leaking 135 pods in the "Success" phase. 

![image](https://user-images.githubusercontent.com/71290498/155384840-f66fd4cb-d207-4ea0-8d9c-99cc60a091a9.png)

Obviously we need to fix the pod leaking issue. But I definitely expected the wavefront metrics here to match what kubernetes actually uses to schedule things. Any idea what is going on here?

Thank you!

**Comment by helen-shao** [comment]
Hi, Thanks for reporting the issue. 
We believe there is a bug in the collector code that’s including completed pods when aggregating the total for `kubernetes.node.cpu.request`. We've created a ticket and will reach out once it's fixed.

**Comment by austinpray-mixpanel** [comment]
Thank you!

**Comment by austinpray-mixpanel** [comment]
Any update?

**Comment by akodali18** [comment]
This should be fixed with https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/pull/384

**Comment by austinpray-mixpanel** [comment]
Thank you!
