### ISSUE TITLE
No kubernetes.pod.network.tx with TKG on AWS

### ISSUE THREAD

**Issue by arnavc1712** [wavefrontHQ/wavefront-collector-for-kubernetes#371]
Hi,
We are deploying TKG on AWS along with the Wavefront Collector for Kubernetes. We do not seem to be getting kubernetes.pod.network.tx  and kubernetes.pod.network.rx  metrics. How do we fix this?

**Comment by priyaselvaganesan** [comment]
We are tracking this issue in [K8SSAAS-1052](https://jira.eng.vmware.com/browse/K8SSAAS-1052). We will update here on status as we prioritize and look at this issue.

**Comment by mmichael** [comment]
@arnavc1712  Normally this in an issue with the local TKG Kubernetes metrics server not returning network metrics. 

Can you run the following: 
`kubectl get --raw /api/v1/nodes/${NODE_NAME}/proxy/stats/summary | jq '.' > stats_summary.json`

And check to see if your environment returns pod level network metrics locally. They should be at the following hierarchy pods.network.txBytes or pods.network.rxBytes. If no network metrics or zero values are being returned then you need to figure out why your TKG on AWS local metric server is not returning network data.  

The Wavefront Collector for Kubernetes relies on the network metric data being returned via the Kubernetes node/../proxy/status/summary api endpoint.
