### ISSUE TITLE
Info about required resources per cluster or per node

### ISSUE THREAD

**Issue by MoSehsah** [wavefrontHQ/wavefront-collector-for-kubernetes#469]
Hi Team

Is there any information on how much resources the agent needs for a given cluster or per Node? 

I appreciate your support here.

Thanks

**Comment by josephgee** [comment]
Hi @MoSehsah! This is highly variable based on your environment. Many collectors run with as little as 200Mb memory per instance, but leaders can be more demanding, and what rules, what targets, and what volume of metrics they are producing makes is very hard to provide a hard and fast rule. Some datasources, such as istio, produce a very high volume and that affects the ultimate resource use. We have seen some environments push up to 2Gb.

**Comment by priyaselvaganesan** [comment]
@MoSehsah, if you have any more questions, please feel free to re-open this issue with details on your environment.
