### ISSUE TITLE
Collector stopped getting hpa.* metrics

### ISSUE THREAD

**Issue by jeesmon** [wavefrontHQ/wavefront-collector-for-kubernetes#556]
We recently updated collector to a new version (we were running with a quite old version before) and we stopped getting hpa.* metrics. Our kubernetes version is 1.22. Looks like it happened after this commit: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/pull/432/files (change from v2beta1 -> v2beta2)

We can see collector showing the following error log

```
time="2023-01-26T00:04:18Z" level=error msg="invalid type: *v2beta1.HorizontalPodAutoscaler"
```

So I'm assuming our cluster is still returning `v2beta1.HorizontalPodAutoscaler` and type casting to `v2beta2.HorizontalPodAutoscaler` is failing.

Any advice on fixing this issue? Any insight on why version for HPA is changed from v2beta1 -> v2beta2? Is it due to kubernetes version supportability?

Thanks!

**Comment by jeesmon** [comment]
@Jyuqi @mmichael @priyaselvaganesan Could you please take look? Thanks!

**Comment by priyaselvaganesan** [comment]
Hello @jeesmon, Thank you for brining this up! We will review the PR and look to get a fix in the upcoming releases.
