### ISSUE TITLE
Add examples to autodiscovery

### ISSUE THREAD

**Issue by kmistry3** [wavefrontHQ/wavefront-collector-for-kubernetes#63]
Hi, 
Currently, the Auto discovery page is https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/discovery.md has details about many different ways in which pods can be auto-discovered. It would be great to have some examples for the same.

For example: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/configuration.md#prometheus_source has examples to define the prometheus sources. 

There are some example configuration files in the links below. I would like to request some examples under the `discovery:` section
https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/d6a73808a32d72d9268e8c18204287f9515ad413/deploy/kubernetes/4-collector-config.yaml#L87

https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/deploy/examples/conf.example.yaml#L82

**Comment by vikramraman** [comment]
Added an example around how to annotate pods to be autodiscovered by the Collector: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/commit/d15aa63f6afb5700fb2e02b630d73e1948407df6
