### ISSUE TITLE
Missing kubernetes.pod_container.accelerator.request metrics

### ISSUE THREAD

**Issue by gavinbunney** [wavefrontHQ/wavefront-collector-for-kubernetes#64]
The `kubernetes.pod_container.accelerator.request` metrics [mentioned in the docs](https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/metrics.md#kubernetes-source) for `pod_container` is missing. There doesn't appear to be any references to that metric in code, also confirmed that it's not available in our Wavefront instance.

Could this be added? Thanks!

**Comment by vikramraman** [comment]
Thanks for raising the issue! Would have to look into this a bit before getting back.

**Comment by vikramraman** [comment]
@gavinbunney The GPU request metric should be under `kubernetes.pod_container.<GPU_DEVICE>.request` etc. For example: `kubernetes.pod_container.nvidia.com.gpu.request`.

**Comment by gavinbunney** [comment]
Thanks @vikramraman ! Confirmed those metrics are available
