### ISSUE TITLE
Request to include examples for configuration of plugins under telegraf_source

### ISSUE THREAD

**Issue by kmistry3** [wavefrontHQ/wavefront-collector-for-kubernetes#65]
Hi,

I'd like to request some examples for configuring plugins under telegraf_source for the Wavefront Collector for Kubernetes.

The configuration page currently does not have examples on how to configure plugins on a per plugin basis.
https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/configuration.md

Requesting examples for plugin config in the config.yaml file in the link below:
https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/d15aa63f6afb5700fb2e02b630d73e1948407df6/deploy/kubernetes/4-collector-config.yaml

Thank you!

**Comment by vikramraman** [comment]
Done: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/commit/79643db930cfff1e2f1aa39f79f3ca6bddde1fae
