### ISSUE TITLE
helm collector discovery unable to distinguish between pods in different namespaces

### ISSUE THREAD

**Issue by andrehuman** [wavefrontHQ/wavefront-collector-for-kubernetes#66]
We have a kubernetes cluster running with nodes [kube01, kube02, kube03], with two different namespaces each for one of our development stages,  backend-ed and backend-rc. 

With this we have certain service deployments that require pod names that are static and follow a specific sequence / pattern, eg. [aservice-0, aservice-1] and [bservice-0, bservice-1] etc.

We have tried various approaches to deploy the wavefront collector with the helm charts, but we keep on running into the same issue. The issue is as follows.

When we have pods aservice-0 and aservice-1 running on backend-ed as well as on backend-rc there is the off chance, in our case, that two pods with the same name are created on the same underlying node.

pod -> namespace -> node

aservice-1 -> backend-ed -> kube02
aservice-1 -> backend-rc -> kube02
 
This causes the collector to only collect metrics for one of the pods. In the collector logs we can see that the pods are added, and then almost instantly removed. 

When we leave it running for a couple of hours you can clearly see metrics for either one of them, but not both. 

Here is an example of the log output:
 
time="2020-05-20T10:03:39Z" level=debug msg="handling resource" kind=pod name=aservice-1 namespace=backend-ed
time="2020-05-20T10:03:39Z" level=debug msg="name: prometheus_metrics_provider: pod-aservice-1:8081 discovered: rule"
time="2020-05-20T10:03:39Z" level=info msg="Adding provider" collection_interval=10s name="prometheus_metrics_provider: pod-aservice-1:8081" timeout=5s
time="2020-05-20T10:03:39Z" level=debug msg="handling resource" kind=pod name=aservice-1 namespace=backend-rc
time="2020-05-20T10:03:39Z" level=debug msg="deleting endpoint" endpoint="pod-aservice-1:8081" type=prometheus
time="2020-05-20T10:03:39Z" level=info msg="Deleted provider" name="prometheus_metrics_provider: pod-aservice-1:8081"
time="2020-05-20T10:03:39Z" level=debug msg="name: prometheus_metrics_provider: pod-aservice-1:8081 discovered: rule"
time="2020-05-20T10:03:39Z" level=info msg="Adding provider" collection_interval=10s name="prometheus_metrics_provider: pod-aservice-1:8081" timeout=5s
time="2020-05-20T10:03:40Z" level=debug msg="handling resource" kind=service name=aservice namespace=backend-ed
time="2020-05-20T10:03:40Z" level=debug msg="prometheus scrape=false for service=aservice"
time="2020-05-20T10:03:40Z" level=debug msg="no endpoint changes for backend-ed-service-aservice"
time="2020-05-20T10:03:40Z" level=debug msg="handling resource" kind=service name=aservice namespace=backend-rc
time="2020-05-20T10:03:40Z" level=debug msg="prometheus scrape=false for service=aservice"
time="2020-05-20T10:03:40Z" level=debug msg="no endpoint changes for backend-rc-service-aservice"

Do you by any chance have an idea what we can do to resolve this, besides from renaming the pods?

**Comment by vikramraman** [comment]
@andrehuman We currently use `podName:port` as a unique key within maps along the discovery code path. So if two pods share the same name:port, we'll end up collecting from only one.

One workaround (other than renaming the pods) would be to change the port on which the metrics are exposed/scraped from. You can then add a [prometheus.io/port](https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/discovery.md#annotation-based-discovery) annotation to the relevant pods if this is possible.

**Comment by andrehuman** [comment]
@vikramraman unfortunately changing the port is not really an option at the moment. 

won't it be possible to include the namespace into the unique key? 

Or force the collector to look at a namespace exclusively and not discover the other pods etc? 

As mentioned we ran numerous test, one of which was to strip out all extra metric collectors eg. kube.*, coredns, kubedns etc and create collectors for each namespace paired with a local proxy that filtered out all other metrics that doesn't have our own prefix that we added. This test only showed that regardless off the namespace specified, the collectors still look at other namespaces when discovering metrics.

**Comment by vikramraman** [comment]
Yes, we could probably include the namespace as an enhancement. My comment was to suggest a workaround based on existing behavior.

You can limit discovery to a particular namespace using [discovery rules selectors](https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/discovery.md#rule-based-discovery).

Will look into including the namespace within the key and get back on that.

**Comment by andrehuman** [comment]
Thanks for the update.

All of our test had the discovery  selector.namespaces set to the ones we wanted. But unfortunately that didn't help much. Turns out even though the namespace is set, the discovery process still somehow figures out that there is a different namespace that has the same podName:port

We did discuss the workaround suggestion, but that would not work in our implementation.

**Comment by vikramraman** [comment]
@andrehuman could you try `wavefronthq/wavefront-kubernetes-collector:1.1.1-rc2`?

It includes a potential fix for this issue: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/commit/e7714014163be30e21a22aee0d9a8684d0444f76

**Comment by andrehuman** [comment]
@vikramraman thanks for the quick response on this. 

After deploying the updated collector version 1.1.1-rc2 I am seeing a steady stream of metrics in wavefront for the above pods. I will leave it running over night and have a closer look at the metrics and the collector logs in the morning. I will provide an update as soon as possible.

**Comment by andrehuman** [comment]
HI @vikramraman thanks for the quick resolution. The metric flow has been constant the whole day.

**Comment by vikramraman** [comment]
Thanks for the confirmation. Will release v1.1.1 shortly with the fix.
