### ISSUE TITLE
Not seeing metrics after cluster name change

### ISSUE THREAD

**Issue by abhishekpolavarpu** [wavefrontHQ/wavefront-collector-for-kubernetes#81]
Hi Team,

I was using this to push my cluster metrics to wavefront. During the initial setup, i had ClusterA as clustername in configmap and the metrics started flowing fine. I changed the cluster name to ClusterB and restarted daemon set and wavefront proxy. Now I cant see the new clustername in wavefront or any of the cluster related metrics. Also, I don't see any any errors either in wavefront proxy or collector pods.

**Comment by abhishekpolavarapu** [comment]
Apologies, this can be closed. I solved my issue by setting:
kubeletPort: 10255
kubeletHttps: false

It's wierd for some cluster read/write kubelet port worked and for some it doesnt

**Comment by vikramraman** [comment]
Thanks for the follow up. Comes down to which port the kubelet has enabled (secure port 10250 vs insecure 10255). We default to the secure option in the configs.
