### ISSUE TITLE
Add feature to read from secrets to send passwords to configs

### ISSUE THREAD

**Issue by mhoshi-vm** [wavefrontHQ/wavefront-collector-for-kubernetes#83]
Hi we are using the wavefront collector plugin but we like to have a way to be able to read these parameters from kuberntes secrets instead of writing it in a yaml file

https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/deploy/examples/conf.example.yaml#L160

**Comment by vikramraman** [comment]
Thanks for raising the issue. We have an internal ticket to address this. Will keep this open until it is done.
