### ISSUE TITLE
Feature Request: Add support for windows nodes

### ISSUE THREAD

**Issue by perithompson** [wavefrontHQ/wavefront-collector-for-kubernetes#85]
The wavefront collector currently only supports Linux nodes, but as Kubernetes for windows was [GA for production in 1.14](https://kubernetes.io/blog/2019/03/25/kubernetes-1-14-release-announcement/) it would be good to get a way of integrating this into Wavefront Kubernetes collector.  When we add windows nodes they are note detected and the collector is unable to deploy onto the cluster.  There may be workarounds available such as deploying a [telegraf](https://docs.wavefront.com/windows.html) or [Prometheus](https://github.com/prometheus-community/windows_exporter) collector but this would still require updates to the default dashboard.

Is there a recommended workaround in place for windows nodes that we can use in the meantime?

**Comment by perithompson** [comment]
I managed to compile the collector on windows but it panics straight away
`c:\Temp>wavefront-collector.exe
time="2021-01-18T07:49:57-08:00" level=info msg=wavefront-collector.exe 
time="2021-01-18T07:49:57-08:00" level=info msg="wavefront-collector version "
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getVersion(0x4)
        c:/code/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:279
 +0x1f8
main.registerVersion()
        c:/code/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:272
 +0x29
main.preRegister(0xc0005620b0)
        c:/code/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:101
 +0x52
main.main()
        c:/code/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:80 
+0x27c`

**Comment by perithompson** [comment]
I have compiled this on windows and ran this on the host and I have some success it monitoring the node.  We can use [wins](https://github.com/rancher/wins/) if privileged host access is required to get this started but privileged containers are slated for 1.21

![image](https://user-images.githubusercontent.com/11655452/104948189-d061fc80-59b4-11eb-822f-cd7d11a7b3b8.png)

**Comment by perithompson** [comment]
I have not got this running in a pod (doesn't seem to require escalation on the host for the kubernetes metrics) however it looking like kubernetes.pod.memory.usage is 0.000 for all windows pods. 

Working set is taking measurements, as is cpu so I believe that there may be a problem with that particular metric

**Comment by vikramraman** [comment]
@perithompson Are there any Linux nodes in the mix? The Collector can also be run as a deployment (instead of a daemonset). Assuming there are Linux nodes, this is a workaround that can be used to monitor the windows worker nodes as well.

**Comment by perithompson** [comment]
Hi @vikramraman, there may be some users that would prefer to keep the clusters limited to only having the Linux control plane and no worker nodes, so it would be best to try and get something for all use cases or at least some mention in the docs on windows support.  It seems that the collector works on windows so it would just be the ci and build that would need to change.  Is windows support via daemonset on the roadmap?

Also, have you seen the kubernetes.pod.memory.usage problem before.

**Comment by vikramraman** [comment]
We investigated supporting Windows last year. There were no technical issues, but we ran into some legal issues in distributing Windows containers. We settled on a workaround (that we recommend at this time) to run the Collector as a deployment (requires one linux node in the cluster) and use that to monitor the windows worker nodes/workloads.

The helm chart supports deployment by toggling this [property](https://github.com/wavefrontHQ/helm/blob/50e8e5d7ee20d94fdb318922e6c7f926a8d1b271/wavefront/values.yaml#L36).

**Comment by perithompson** [comment]
thanks @vikramraman, it would be good to understand this a little bit more but I will give it a go, are there any downsides to the deployment method, aside from the resourcing on the one node and the need to have a non control plane linux node?


I think this may be a cadvisor issue but any ideas what may be causing this? 
>  it looking like kubernetes.pod.memory.usage is 0.000 for all windows pods.

**Comment by perithompson** [comment]
@vikramraman Do you know why the kubernetes.pod.memory.usage is 0.000 would be 0, can you confirm what endpoint the stats are collected from,  it looks like /stats/summary
![image](https://user-images.githubusercontent.com/11655452/107390784-f3815700-6aef-11eb-9233-08f487f443e6.png)
has the information and so does /metrics/resource so I'm not sure why the memory might be zeroed

**Comment by vikramraman** [comment]
Yes, we collect from /stats/summary. @JSchuenke can assist with further queries.
